### ISSUE TITLE
Can't change rep.

### ISSUE THREAD

**Issue by tkepner** [BananoCoin/camo-banano-light-wallet#36]
I wanted to change the rep (so that I could use jungleTV, which uses the rep-change procedure to verify you really own the wallet without exchanging coins, then you change back to your previous rep or a new one). I'm using the Light (Basic) wallet.

I copy in the new rep, hit update representative, and I get a blank box with the OKAY button.

And nothing changes.

**Comment by ghost** [comment]
fixed in 1.1.8

**Comment by ghost** [comment]
https://github.com/BananoCoin/camo-banano-light-wallet/releases/tag/v1.1.8

**Comment by tkepner** [comment]
Thank you for your hard work, and quick response.


-----Original Message-----
