### ISSUE TITLE
Manual Receive screen is bigger than two monitors!

### ISSUE THREAD

**Issue by tkepner** [BananoCoin/camo-banano-light-wallet#37]
I load Light Camo. I give it my seed. The Home screen appears. I go to Receive and a list of "Pending Actions" appears. Auto-Receive is enabled, but nothing is happening. After an hour, I still see no changes. I click Disable Auto-receive. The next screen is bigger than both my monitors, with a ton of wasted space. (see included screen-capture).
![camo_bug](https://user-images.githubusercontent.com/63252815/133460250-99f48365-0622-4730-b832-fe865e926ff1.jpg)

**Comment by ghost** [comment]
fixed, but until a new release is made by suggestion is to use three monitors.
